package com.oracle.curd.bean;

import java.util.Date;

public class Ckin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckin.inid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String inid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckin.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckin.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckin.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckin.indate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckin.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckin.inid
     *
     * @return the value of ckin.inid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckin.inid
     *
     * @param inid the value for ckin.inid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setInid(String inid) {
        this.inid = inid == null ? null : inid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckin.proid
     *
     * @return the value of ckin.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckin.proid
     *
     * @param proid the value for ckin.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckin.pname
     *
     * @return the value of ckin.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckin.pname
     *
     * @param pname the value for ckin.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckin.num
     *
     * @return the value of ckin.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckin.num
     *
     * @param num the value for ckin.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckin.indate
     *
     * @return the value of ckin.indate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckin.indate
     *
     * @param indate the value for ckin.indate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckin.marks
     *
     * @return the value of ckin.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckin.marks
     *
     * @param marks the value for ckin.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    @Override
    public String toString() {
        return "Ckin{" +
                "inid='" + inid + '\'' +
                ", proid='" + proid + '\'' +
                ", pname='" + pname + '\'' +
                ", num=" + num +
                ", indate=" + indate +
                ", marks='" + marks + '\'' +
                '}';
    }
}