package com.oracle.curd.bean;

import java.util.Date;

public class Ckretire {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.inid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String inid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.indate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.retdate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date retdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.reason
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ckretire.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.inid
     *
     * @return the value of ckretire.inid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.inid
     *
     * @param inid the value for ckretire.inid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setInid(String inid) {
        this.inid = inid == null ? null : inid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.proid
     *
     * @return the value of ckretire.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.proid
     *
     * @param proid the value for ckretire.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.pname
     *
     * @return the value of ckretire.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.pname
     *
     * @param pname the value for ckretire.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.num
     *
     * @return the value of ckretire.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.num
     *
     * @param num the value for ckretire.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.indate
     *
     * @return the value of ckretire.indate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.indate
     *
     * @param indate the value for ckretire.indate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.retdate
     *
     * @return the value of ckretire.retdate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getRetdate() {
        return retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.retdate
     *
     * @param retdate the value for ckretire.retdate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setRetdate(Date retdate) {
        this.retdate = retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.reason
     *
     * @return the value of ckretire.reason
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.reason
     *
     * @param reason the value for ckretire.reason
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ckretire.marks
     *
     * @return the value of ckretire.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ckretire.marks
     *
     * @param marks the value for ckretire.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}