package com.oracle.curd.bean;

import java.util.Date;

public class Cusretire {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.saleid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String saleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.total
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.saledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date saledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.retdate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date retdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.reason
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.saleid
     *
     * @return the value of cusretire.saleid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.saleid
     *
     * @param saleid the value for cusretire.saleid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSaleid(String saleid) {
        this.saleid = saleid == null ? null : saleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.proid
     *
     * @return the value of cusretire.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.proid
     *
     * @param proid the value for cusretire.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.pname
     *
     * @return the value of cusretire.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.pname
     *
     * @param pname the value for cusretire.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.price
     *
     * @return the value of cusretire.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.price
     *
     * @param price the value for cusretire.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.num
     *
     * @return the value of cusretire.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.num
     *
     * @param num the value for cusretire.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.total
     *
     * @return the value of cusretire.total
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.total
     *
     * @param total the value for cusretire.total
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.saledate
     *
     * @return the value of cusretire.saledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getSaledate() {
        return saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.saledate
     *
     * @param saledate the value for cusretire.saledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSaledate(Date saledate) {
        this.saledate = saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.retdate
     *
     * @return the value of cusretire.retdate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getRetdate() {
        return retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.retdate
     *
     * @param retdate the value for cusretire.retdate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setRetdate(Date retdate) {
        this.retdate = retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.reason
     *
     * @return the value of cusretire.reason
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.reason
     *
     * @param reason the value for cusretire.reason
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.marks
     *
     * @return the value of cusretire.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.marks
     *
     * @param marks the value for cusretire.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}