package com.oracle.curd.bean;

public class Custom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.cusid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.cusname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String cusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.person
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.address
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.emali
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String emali;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.cusid
     *
     * @return the value of custom.cusid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.cusid
     *
     * @param cusid the value for custom.cusid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setCusid(String cusid) {
        this.cusid = cusid == null ? null : cusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.cusname
     *
     * @return the value of custom.cusname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getCusname() {
        return cusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.cusname
     *
     * @param cusname the value for custom.cusname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setCusname(String cusname) {
        this.cusname = cusname == null ? null : cusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.tel
     *
     * @return the value of custom.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.tel
     *
     * @param tel the value for custom.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.person
     *
     * @return the value of custom.person
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.person
     *
     * @param person the value for custom.person
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.address
     *
     * @return the value of custom.address
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.address
     *
     * @param address the value for custom.address
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.emali
     *
     * @return the value of custom.emali
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getEmali() {
        return emali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.emali
     *
     * @param emali the value for custom.emali
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setEmali(String emali) {
        this.emali = emali == null ? null : emali.trim();
    }
}