package com.oracle.curd.bean;

public class Kcxx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcxx.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcxx.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcxx.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kcxx.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcxx.proid
     *
     * @return the value of kcxx.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcxx.proid
     *
     * @param proid the value for kcxx.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcxx.pname
     *
     * @return the value of kcxx.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcxx.pname
     *
     * @param pname the value for kcxx.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcxx.num
     *
     * @return the value of kcxx.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcxx.num
     *
     * @param num the value for kcxx.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kcxx.marks
     *
     * @return the value of kcxx.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kcxx.marks
     *
     * @param marks the value for kcxx.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}