package com.oracle.curd.bean;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inprice
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Double inprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prodate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date prodate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.reledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date reledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.supname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String supname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.protype
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String protype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.unit
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proid
     *
     * @return the value of product.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proid
     *
     * @param proid the value for product.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inprice
     *
     * @return the value of product.inprice
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Double getInprice() {
        return inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inprice
     *
     * @param inprice the value for product.inprice
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setInprice(Double inprice) {
        this.inprice = inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prodate
     *
     * @return the value of product.prodate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getProdate() {
        return prodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prodate
     *
     * @param prodate the value for product.prodate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProdate(Date prodate) {
        this.prodate = prodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.reledate
     *
     * @return the value of product.reledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getReledate() {
        return reledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.reledate
     *
     * @param reledate the value for product.reledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setReledate(Date reledate) {
        this.reledate = reledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.supname
     *
     * @return the value of product.supname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getSupname() {
        return supname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.supname
     *
     * @param supname the value for product.supname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSupname(String supname) {
        this.supname = supname == null ? null : supname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.protype
     *
     * @return the value of product.protype
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProtype() {
        return protype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.protype
     *
     * @param protype the value for product.protype
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProtype(String protype) {
        this.protype = protype == null ? null : protype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unit
     *
     * @return the value of product.unit
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unit
     *
     * @param unit the value for product.unit
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.marks
     *
     * @return the value of product.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.marks
     *
     * @param marks the value for product.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    @Override
    public String toString() {
        return "Product{" +
                "proid='" + proid + '\'' +
                ", pname='" + pname + '\'' +
                ", price=" + price +
                ", inprice=" + inprice +
                ", prodate=" + prodate +
                ", reledate=" + reledate +
                ", supname='" + supname + '\'' +
                ", protype='" + protype + '\'' +
                ", unit='" + unit + '\'' +
                ", marks='" + marks + '\'' +
                '}';
    }
}