package com.oracle.curd.bean;

import java.util.Date;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.saleid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String saleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.total
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.saledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private Date saledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String marks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.cusid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.cusname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String cusname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.saleid
     *
     * @return the value of sale.saleid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.saleid
     *
     * @param saleid the value for sale.saleid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSaleid(String saleid) {
        this.saleid = saleid == null ? null : saleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.proid
     *
     * @return the value of sale.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.proid
     *
     * @param proid the value for sale.proid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.pname
     *
     * @return the value of sale.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.pname
     *
     * @param pname the value for sale.pname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.price
     *
     * @return the value of sale.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.price
     *
     * @param price the value for sale.price
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.num
     *
     * @return the value of sale.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.num
     *
     * @param num the value for sale.num
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.total
     *
     * @return the value of sale.total
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.total
     *
     * @param total the value for sale.total
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setTotal(String total) {
        this.total = total == null ? null : total.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.saledate
     *
     * @return the value of sale.saledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public Date getSaledate() {
        return saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.saledate
     *
     * @param saledate the value for sale.saledate
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSaledate(Date saledate) {
        this.saledate = saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.marks
     *
     * @return the value of sale.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.marks
     *
     * @param marks the value for sale.marks
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.cusid
     *
     * @return the value of sale.cusid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.cusid
     *
     * @param cusid the value for sale.cusid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setCusid(String cusid) {
        this.cusid = cusid == null ? null : cusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.cusname
     *
     * @return the value of sale.cusname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getCusname() {
        return cusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.cusname
     *
     * @param cusname the value for sale.cusname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setCusname(String cusname) {
        this.cusname = cusname == null ? null : cusname.trim();
    }

    @Override
    public String toString() {
        return "Sale{" +
                "saleid='" + saleid + '\'' +
                ", proid='" + proid + '\'' +
                ", pname='" + pname + '\'' +
                ", price=" + price +
                ", num=" + num +
                ", total='" + total + '\'' +
                ", saledate=" + saledate +
                ", marks='" + marks + '\'' +
                ", cusid='" + cusid + '\'' +
                ", cusname='" + cusname + '\'' +
                '}';
    }
}