package com.oracle.curd.bean;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staffid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staffname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String staffname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.card
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.sex
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.stafftype
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String stafftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.pwd
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staffid
     *
     * @return the value of staff.staffid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staffid
     *
     * @param staffid the value for staff.staffid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid == null ? null : staffid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staffname
     *
     * @return the value of staff.staffname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getStaffname() {
        return staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staffname
     *
     * @param staffname the value for staff.staffname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setStaffname(String staffname) {
        this.staffname = staffname == null ? null : staffname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.card
     *
     * @return the value of staff.card
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.card
     *
     * @param card the value for staff.card
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.sex
     *
     * @return the value of staff.sex
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.sex
     *
     * @param sex the value for staff.sex
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.tel
     *
     * @return the value of staff.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.tel
     *
     * @param tel the value for staff.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.stafftype
     *
     * @return the value of staff.stafftype
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getStafftype() {
        return stafftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.stafftype
     *
     * @param stafftype the value for staff.stafftype
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setStafftype(String stafftype) {
        this.stafftype = stafftype == null ? null : stafftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.pwd
     *
     * @return the value of staff.pwd
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.pwd
     *
     * @param pwd the value for staff.pwd
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}