package com.oracle.curd.bean;

public class Supply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.supid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String supid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.suppname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String suppname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.person
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.address
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.emali
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    private String emali;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.supid
     *
     * @return the value of supply.supid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getSupid() {
        return supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.supid
     *
     * @param supid the value for supply.supid
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSupid(String supid) {
        this.supid = supid == null ? null : supid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.suppname
     *
     * @return the value of supply.suppname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getSuppname() {
        return suppname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.suppname
     *
     * @param suppname the value for supply.suppname
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setSuppname(String suppname) {
        this.suppname = suppname == null ? null : suppname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.tel
     *
     * @return the value of supply.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.tel
     *
     * @param tel the value for supply.tel
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.person
     *
     * @return the value of supply.person
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.person
     *
     * @param person the value for supply.person
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.address
     *
     * @return the value of supply.address
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.address
     *
     * @param address the value for supply.address
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.emali
     *
     * @return the value of supply.emali
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public String getEmali() {
        return emali;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.emali
     *
     * @param emali the value for supply.emali
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    public void setEmali(String emali) {
        this.emali = emali == null ? null : emali.trim();
    }
}