package com.oracle.curd.dao;

import com.oracle.curd.bean.Ckin;
import com.oracle.curd.bean.CkinExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CkinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    long countByExample(CkinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByExample(CkinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByPrimaryKey(String inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insert(Ckin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insertSelective(Ckin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    List<Ckin> selectByExample(CkinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    Ckin selectByPrimaryKey(String inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Ckin record, @Param("example") CkinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExample(@Param("record") Ckin record, @Param("example") CkinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKeySelective(Ckin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckin
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKey(Ckin record);

//    List<Ckin> selectByConditions(Ckin ckin);
}