package com.oracle.curd.dao;

import com.oracle.curd.bean.Ckretire;
import com.oracle.curd.bean.CkretireExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CkretireMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    long countByExample(CkretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByExample(CkretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByPrimaryKey(String inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insert(Ckretire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insertSelective(Ckretire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    List<Ckretire> selectByExample(CkretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    Ckretire selectByPrimaryKey(String inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Ckretire record, @Param("example") CkretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExample(@Param("record") Ckretire record, @Param("example") CkretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKeySelective(Ckretire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ckretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKey(Ckretire record);
}