package com.oracle.curd.dao;

import com.oracle.curd.bean.Cusretire;
import com.oracle.curd.bean.CusretireExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CusretireMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    long countByExample(CusretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByExample(CusretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByPrimaryKey(String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insert(Cusretire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insertSelective(Cusretire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    List<Cusretire> selectByExample(CusretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    Cusretire selectByPrimaryKey(String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Cusretire record, @Param("example") CusretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExample(@Param("record") Cusretire record, @Param("example") CusretireExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKeySelective(Cusretire record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cusretire
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKey(Cusretire record);
}