package com.oracle.curd.dao;

import com.oracle.curd.bean.Kcxx;
import com.oracle.curd.bean.KcxxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KcxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    long countByExample(KcxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByExample(KcxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByPrimaryKey(String proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insert(Kcxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insertSelective(Kcxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    List<Kcxx> selectByExample(KcxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    Kcxx selectByPrimaryKey(String proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Kcxx record, @Param("example") KcxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExample(@Param("record") Kcxx record, @Param("example") KcxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKeySelective(Kcxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kcxx
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKey(Kcxx record);
}