package com.oracle.curd.dao;

import com.oracle.curd.bean.Sale;
import com.oracle.curd.bean.SaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    long countByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByPrimaryKey(String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insertSelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    List<Sale> selectByExample(SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    Sale selectByPrimaryKey(String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sale record, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExample(@Param("record") Sale record, @Param("example") SaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKeySelective(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKey(Sale record);
}