package com.oracle.curd.dao;

import com.oracle.curd.bean.Supply;
import com.oracle.curd.bean.SupplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    long countByExample(SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByExample(SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int deleteByPrimaryKey(String supid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insert(Supply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int insertSelective(Supply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    List<Supply> selectByExample(SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    Supply selectByPrimaryKey(String supid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") Supply record, @Param("example") SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByExample(@Param("record") Supply record, @Param("example") SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKeySelective(Supply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbg.generated Wed Dec 23 13:56:28 CST 2020
     */
    int updateByPrimaryKey(Supply record);
}